"use client";

import { ReactNode } from "react";
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppProps } from 'next/app';
import { NextAppDirEmotionCacheProvider } from 'tss-react/next/appDir';
import theme from "@/util/theme";
import DGAppBar from "@/components/DGAppBar";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps extends AppProps {
  children: ReactNode;
  session: any;
}

export default function RootLayout(props : RootLayoutProps) {
  const { children, session } = props;
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <NextAppDirEmotionCacheProvider options={{ key: "css" }}>
          <ThemeProvider theme={theme}>
            <SessionProvider session={session}>
              <DGAppBar>{ children }</DGAppBar>
            </SessionProvider>
          </ThemeProvider>
        </NextAppDirEmotionCacheProvider>
      </body>
    </html>
  )
}
